// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-ecommerce-backend-api/internal/controller"
	"go-ecommerce-backend-api/internal/repository"
	"go-ecommerce-backend-api/internal/service"
)

// Injectors from wire.go:

func InitUserModule() (*controller.UserController, error) {
	iUserRepository := repository.NewUserRepository()
	iUserAuthRepository := repository.NewUserAuthRepository()
	iUserService := service.NewUserService(iUserRepository, iUserAuthRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
