server:
  mode: "dev"
  port: 8001
cors:
  url: "http://localhost:5173"
mysql:
  # host: "mysql-container-go"
  # port: 3306
  host: "127.0.0.1"
  port: 3300
  username: "root"
  password: "shopdev"
  dbname: "shopdevgo"
  maxIdleConns: 3
  maxOpenConns: 5
  connMaxLifeTime: 10
redis:
  # host: "redis-container-go"
  # port: 6379
  host: "127.0.0.1"
  port: 6300
  password: ""
  database: 0
log:
  logLevel: "debug"
  fileLogName: "./storage/logs/server.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 7
  compress: true
jwt:
  tokenHourLifeSpan: 1
  accessSecret: "myaccessecrettoken2025"
  accessSecretExpiriedTime: "1h"
cloudinary:
  cloud_name: "dmsnw2qpd"
  api_key: "214187186256291"
  api_secret: "13ew1sxffolXvVYkaGleJcAd4AY"
admin:
  email: "toilaadmin@gmail.com"
  username: "toilaadmin"
  phoneNumber: "0012345621"
  password: "Toilaadmin@2004"
